server:
  port: 8081

spring:
  application:
    name: SERVICE-CLIENT
  datasource:
    url: jdbc:mysql://localhost:3306/clientdb
    username: root
    password: Houssam123@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      ribbon:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
